### DISCUSSION TITLE
TW4 Button cursor

### DISCUSSION THREAD

**Discussion by nikitaiavdeev** [huntabyte/shadcn-svelte#1952] [General]
Hi all,

I don't know why browsers and tailwind v4 did it, but in my opinion all buttons should have a cursor pointer

Proposing to add it either into global css or into each ui component as a default cursor
```css
@layer base {
  button, [role="button"] {
    cursor: pointer;
  }
}
```
