### ISSUE TITLE
Fix wrong Tailwind utility: change border-border to border-none in Base Layer

### ISSUE THREAD

**Issue by prad-alpukat** [huntabyte/shadcn-svelte#1852]
### Change Type

Correction

### Proposed Changes

https://next.shadcn-svelte.com/docs/installation/manual

### Issue
In the `@layer base` section of the documentation, the utility `@apply border-border` is used.  
However, `border-border` is not a valid Tailwind CSS utility class.

### Solution
Replace:
```css
@apply border-border;
```
with:

```css
@apply border-none;
```
Why
border-border does not exist in Tailwind CSS.
The correct utility for removing borders may is border-none.
Fixing this will prevent build errors and avoid confusion for users following the documentation.

**Comment by prad-alpukat** [comment]
hahaha, i miss  the custom style config. my bad

**Comment by mike-lloyd03** [comment]
I'm getting the same error I was getting for `border-border` with `bg-background` and `text-foreground` now. Is this error related?

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	:root {
		--background: 0 0% 100%;
		--foreground: 222.2 84% 4.9%;

		--muted: 210 40% 96.1%;
		--muted-foreground: 215.4 16.3% 46.9%;

		--popover: 0 0% 100%;
		--popover-foreground: 222.2 84% 4.9%;

		--card: 0 0% 100%;
		--card-foreground: 222.2 84% 4.9%;

		--border: 214.3 31.8% 91.4%;
		--input: 214.3 31.8% 91.4%;

		--primary: 222.2 47.4% 11.2%;
		--primary-foreground: 210 40% 98%;

		--secondary: 210 40% 96.1%;
		--secondary-foreground: 222.2 47.4% 11.2%;

		--accent: 210 40% 96.1%;
		--accent-foreground: 222.2 47.4% 11.2%;

		--destructive: 0 72.2% 50.6%;
		--destructive-foreground: 210 40% 98%;

		--ring: 222.2 84% 4.9%;

		--radius: 0.5rem;
	}

	.dark {
		--background: 222.2 84% 4.9%;
		--foreground: 210 40% 98%;

		--muted: 217.2 32.6% 17.5%;
		--muted-foreground: 215 20.2% 65.1%;

		--popover: 222.2 84% 4.9%;
		--popover-foreground: 210 40% 98%;

		--card: 222.2 84% 4.9%;
		--card-foreground: 210 40% 98%;

		--border: 217.2 32.6% 17.5%;
		--input: 217.2 32.6% 17.5%;

		--primary: 210 40% 98%;
		--primary-foreground: 222.2 47.4% 11.2%;

		--secondary: 217.2 32.6% 17.5%;
		--secondary-foreground: 210 40% 98%;

		--accent: 217.2 32.6% 17.5%;
		--accent-foreground: 210 40% 98%;

		--destructive: 0 62.8% 30.6%;
		--destructive-foreground: 210 40% 98%;

		--ring: 212.7 26.8% 83.9%;
	}
}

@layer base {
	* {
		@apply border-none;
	}
	body {
		@apply bg-background text-foreground;
	}
}
```
