### ISSUE TITLE
Button has no "cursor-pointer" in @next version

### ISSUE THREAD

**Issue by Padi2312** [huntabyte/shadcn-svelte#1989]
### Describe the bug

Previously the button had the "cursor-pointer" class.
No it hasn't this class anymore. 

### Reproduction

pnpm dlx shadcn-svelte@next init

pnpm dlx shadcn-svelte@next add button

### Logs

```bash

```

### System Info

```bash
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 30.19 GB / 47.93 GB
  Binaries:
    Node: 23.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.6.3 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (135.0.3179.73)
    Internet Explorer: 11.0.26100.1882
```

### Severity

annoyance

**Comment by ieedan** [comment]
It mirrors the behavior of native components better

**Comment by sergioponguta** [comment]
Use this on `global.css`

```css
@layer base {
  button:not([disabled]),
  [role="button"]:not([disabled]) {
    cursor: pointer;
  }
}
```
