### ISSUE TITLE
bug(Sidebar): potential issue with theming

### ISSUE THREAD

**Issue by ollema** [huntabyte/shadcn-svelte#2015]
### Describe the bug

hello!

when updating an app from tailwind 3 to tailwind 4 I noticed that many sidebar components had transparent backgrounds.

this was despite having a `bg-sidebar` everywhere.

I wonder if this issue is due to the fact that in the migration guide we are instructed to apply the following tailwind theme:
```css
@theme inline {
  --color-sidebar-background: var(--sidebar-background);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
}
```

I am far from a tailwind 4 expert, in fact this is the first time I migrate something to tailwind 4, but I believe that with this theme definition there is nothing created for `bg-sidebar` but instead `bg-sidebar-background`.

when I switch to:
```diff
@theme inline {
-  --color-sidebar-background: var(--sidebar-background);
+  --color-sidebar-: var(--sidebar-background);
}
```
then `bg-sidebar` seems to work and everything looks much better.

based on upstream `shadcn/ui` it looks to me like they also use `bg-sidebar` so I am assuming that the "bug" here is simply a documentation typo (outlined above).

I am still investigating so not 100% sure though

### Reproduction

n/a

### Logs

```bash

```

### System Info

```bash
System:
    OS: macOS 15.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 398.77 MB / 32.00 GB
    Shell: 4.0.2 - /opt/homebrew/bin/fish
  Binaries:
    Node: 23.11.0 - /opt/homebrew/bin/node
    npm: 10.9.2 - /opt/homebrew/bin/npm
    pnpm: 9.15.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 136.0.7103.114
    Safari: 18.4
  npmPackages:
    @sveltejs/kit: ^2.21.1 => 2.21.1 
    bits-ui: ^1.8.0 => 1.8.0 
    formsnap: ^2.0.1 => 2.0.1 
    mode-watcher: ^1.0.7 => 1.0.7 
    svelte: ^5.33.2 => 5.33.2 
    svelte-sonner: ^1.0.3 => 1.0.3 
    sveltekit-superforms: ^2.25.0 => 2.25.0 
    tailwindcss: ^4.1.7 => 4.1.7 
    vaul-svelte: 1.0.0-next.7 => 1.0.0-next.7
```

### Severity

annoyance
