### ISSUE TITLE
`<Form.NativeSelect>` doesn't properly render arrow svg

### ISSUE THREAD

**Issue by pheuter** [huntabyte/shadcn-svelte#305]
### Current Behavior

`<Form.NativeSelect>` appears to improperly position the down arrow for the select component absolutely on the page.

```svelte
<Form.Item>
	<Form.Label>Notify Employee</Form.Label>
	<Form.NativeSelect required class="w-full">
		<option value={null}>Select</option>
		{#each data.reminderRecipients as employee}
			<option value={employee.id}>{employee.lastName}, {employee.firstName}</option>
		{/each}
	</Form.NativeSelect>
	<Form.Validation />
</Form.Item>
```

<img width="695" alt="Screenshot 2023-09-19 at 4 40 01 PM" src="https://github.com/huntabyte/shadcn-svelte/assets/92698/3dc475d2-aedf-4639-aa3d-68a1a07bcb98">

### Expected Behavior

The down arrow should render inline with the native select component and not be absolutely positioned on the page.

### Steps To Reproduce

See sample code above.

**Comment by huntabyte** [comment]
If you give the `NativeSelect` a "relative" class does that fix the issue? If so then would it make sense to make it relative by default?

Either that or providing the arrow separately for customization might be beneficial. What do you think @pheuter?

**Comment by pheuter** [comment]
Separately might be the way to go, I ended up removing the `<ChevronDown>` icon from the `NativeSelect` component and added a global style in app.css that I borrowed from Tailwind Forms plugin:

```css
select {
	background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
	background-position: right 0.5rem center;
	background-repeat: no-repeat;
	background-size: 1.5em 1.5em;
	padding-right: 2.5rem;
}
```
