### ISSUE TITLE
Question: Why does dark mode requires the ModeWatcher?

### ISSUE THREAD

**Issue by DrMagPie** [huntabyte/shadcn-svelte#586]
Hi, 

Why does dark mode requires the ModeWatcher?
I do understand that it can be used to allow users to change the mode manually.
But let's say we don't want to allow users to do that and the web application should use the system theme/mode.
In that case, I don't really understand why is it required...
As the desired behavior can be achieved with using media query `@media (prefers-color-scheme: dark)` without any dependencies.

```css
@layer base {
	:root {
		--background: 0 0% 100%;
		--foreground: 222.2 84% 4.9%;

		--muted: 210 40% 96.1%;
		--muted-foreground: 215.4 16.3% 46.9%;

		--popover: 0 0% 100%;
		--popover-foreground: 222.2 84% 4.9%;

		--card: 0 0% 100%;
		--card-foreground: 222.2 84% 4.9%;

		--border: 214.3 31.8% 91.4%;
		--input: 214.3 31.8% 91.4%;

		--primary: 222.2 47.4% 11.2%;
		--primary-foreground: 210 40% 98%;

		--secondary: 210 40% 96.1%;
		--secondary-foreground: 222.2 47.4% 11.2%;

		--accent: 210 40% 96.1%;
		--accent-foreground: 222.2 47.4% 11.2%;

		--destructive: 0 72.2% 50.6%;
		--destructive-foreground: 210 40% 98%;

		--ring: 222.2 84% 4.9%;

		--radius: 0.5rem;
	}

	/* If user prefers a dark appearance */
	@media (prefers-color-scheme: dark) {
		:root {
			--background: 222.2 84% 4.9%;
			--foreground: 210 40% 98%;

			--muted: 217.2 32.6% 17.5%;
			--muted-foreground: 215 20.2% 65.1%;

			--popover: 222.2 84% 4.9%;
			--popover-foreground: 210 40% 98%;

			--card: 222.2 84% 4.9%;
			--card-foreground: 210 40% 98%;

			--border: 217.2 32.6% 17.5%;
			--input: 217.2 32.6% 17.5%;

			--primary: 210 40% 98%;
			--primary-foreground: 222.2 47.4% 11.2%;

			--secondary: 217.2 32.6% 17.5%;
			--secondary-foreground: 210 40% 98%;

			--accent: 217.2 32.6% 17.5%;
			--accent-foreground: 210 40% 98%;

			--destructive: 0 62.8% 30.6%;
			--destructive-foreground: 210 40% 98%;

			--ring: hsl(212.7, 26.8%, 83.9);
		}
	}
}
```

Am I missing something? or this is just a matter of preference?
