### ISSUE TITLE
Alert Dialog - When scrollbar disappears page content shifts (MS Edge)

### ISSUE THREAD

**Issue by JershDervis** [huntabyte/shadcn-svelte#92]
### Current Behavior

When opening an alert dialog and a scrollbar exists, the scrollbar will disappear and cause all existing page content to shift the size of the scrollbar.

I've tested this on **Microsoft Edge** and the issue occurs.
It doesn't appear to occur using Chrome.

### Expected Behavior

Existing background content shouldn't move when launching the alert dialog.

### Steps To Reproduce

Using Microsoft Edge Browser (Version 114.0.1823.41)
You can compare the original shadcdn to the svelte version, in the original, this doesn't occur:
Original Alert Dialog: https://ui.shadcn.com/docs/components/alert-dialog
Svelte Alert Dialog: https://www.shadcn-svelte.com/docs/components/alert-dialog

Watch the background content when you click the 'Show Dialog' button.
![F028AB2E-7032-4514-AD7E-68DE66935873](https://github.com/huntabyte/shadcn-svelte/assets/12910980/0ed95072-6bdf-4bef-99da-26d65a049416)

The same is also occurring for the Dialog and Sheet components.
Dialog: https://www.shadcn-svelte.com/docs/components/dialog
Sheet: https://www.shadcn-svelte.com/docs/components/sheet

**Comment by JershDervis** [comment]
The same is also occurring for the Dialog and Sheet components.
Dialog: https://www.shadcn-svelte.com/docs/components/dialog
Sheet: https://www.shadcn-svelte.com/docs/components/sheet

**Comment by huntabyte** [comment]
I've noticed that as well, it's interesting it only occurs in edge (as far as we know). If anyone wants to assist with trying to fix this let me know, otherwise, I'll investigate when I can!

**Comment by weavdale** [comment]
I get this as well on Firefox (latest) on Mac. I looked at shadcn's implementation and I noticed he dynamically inserts this css into the document head to account for the screen jump when the scroll bar is hidden.

```css
<style type="text/css">
  .with-scroll-bars-hidden {
   overflow: hidden !important;
   padding-right: 15px !important;
  }
  body {
    overflow: hidden !important;
    overscroll-behavior: contain;
    position: relative !important;
    padding-left: 0px;
    padding-top: 0px;
    padding-right: 0px;
    margin-left:0;
    margin-top:0;
    margin-right: 15px !important;
    
  }
  
  .right-scroll-bar-position {
    right: 15px !important;
  }
  
  .width-before-scroll-bar {
    margin-right: 15px !important;
  }
  
  .right-scroll-bar-position .right-scroll-bar-position {
    right: 0 !important;
  }
  
  .width-before-scroll-bar .width-before-scroll-bar {
    margin-right: 0 !important;
  }
  
  body {
    --removed-body-scroll-bar-size: 15px;
  }
</style>
```

**Comment by huntabyte** [comment]
@weavdale do you know where he does that exactly? I'm looking for it now!

**Comment by huntabyte** [comment]
So it looks like Radix might be handling that somehow? I'm not seeing anywhere in shad's code where _he's_ injecting the styles. I do have a temporary solution for the time being until we can sort this out with the Radix team (or determine a more elegant way to handle this).

Here's the temp fix:
```css
/* app.postcss */
html {
	scrollbar-gutter: stable;
}
```
